---
gemlists:
  sixarm_gems:
    - Colorful: http://github.com/sixarm/sixarm_ruby_colorful
    - HTML: http://github.com/sixarm/sixarm_ruby_html
    - PasswordText: http://github.com/sixarm/sixarm_ruby_password_text
    - PersonName: http://github.com/sixarm/sixarm_ruby_person_name
    - SpreadsheetHelpers: http://github.com/sixarm/sixarm_ruby_spreadsheeting
    - Unaccent: http://github.com/sixarm/sixarm_ruby_unaccent
  all_other_gems:
    - Rails 3: http://rubyonrails.com
    - Sqlite3-ruby: http://github.com/jamis/sqlite3-ruby
    - ShowFor: http://github.com/plataformatec/show_for
    - hirb: http://github.com/cldwalker/hirb
    - MetaSearch: http://github.com/ernie/meta_search
  test_other_gems:
    - Rspec-rails 2.0 beta: http://github.com/dchelimsky/rspec-rails
    - Faker: http://faker.rubyforge.org/
    - autotest: http://www.zenspider.com/ZSS/Products/ZenTest/
    - shoulda (bmaddys rails3 branch): http://github.com/bmaddy/shoulda
    - Capybara: http://github.com/jnicklas/capybara
    - DatabaseCleaner: http://github.com/bmabey/database_cleaner
    - Cucumber-Rails: http://github.com/aslakhellesoy/cucumber-rails
  js_libs:
    - jQuery: http://jquery.com
    - DD_roundies: http://www.dillerdesign.com/experiment/DD_roundies/
    - gMap: http://gmap.nurtext.de
